# 1. Puerto del Gateway
server.port=8080

# 2. Logs para ver si las rutas y la seguridad funcionan
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.security=DEBUG

# 3. Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://127.0.0.1:8084/realms/carinosas-realm

