server.port=8085
spring.application.name=workflow-service


spring.datasource.url=jdbc:h2:file:/data/workflowdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# URL del Case Service para validar existencia de casos
case.service.url=http://case-service:8081