# Nombre del microservicio y puerto
spring.application.name=evidence-service
server.port=8082


spring.datasource.url=jdbc:h2:file:/data/evidencedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Permitir que Spring cree las tablas autom�ticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar la consola web
spring.h2.console.enabled=true

# URL del Case Service para validar existencia de casos
case.service.url=http://case-service:8081