spring.application.name=people-service
# Usamos el 8083 para no chocar con los otros
server.port=8083

spring.datasource.url=jdbc:h2:file:/data/peopledb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# URL del Case Service para validar existencia de casos
case.service.url=http://case-service:8081